### ISSUE TITLE
Having troubles sending encoding requests

### ISSUE THREAD

**Issue by Zonalds** [PatrickKalkman/MiniVideoEncoder#123]
Hey Patrick.

Amateur here, I am having troubles sending encoding request via the API. I would get this response:

`{
    "statusCode": 415,
    "code": "FST_ERR_CTP_INVALID_MEDIA_TYPE",
    "error": "Unsupported Media Type",
    "message": "Unsupported Media Type: application/x-www-form-urlencoded"
}`

I passed a .webm and a .mp4
Can you send a sample code of what a request form (and value) would look like?

**Comment by PatrickKalkman** [comment]
Hi Paschal, could you try it with encodingType="libx265"?

**Comment by Zonalds** [comment]
I tried it, it returns same error.

**Comment by Zonalds** [comment]
I was able to figure out the problem - I changed `content-type` to `application\json` and that worked. 

However, I get the this:

`[1598440388440] INFO  (18994 on paschal): Processing workflow jobs
[1598440391117] INFO  (18994 on paschal): There are 0 new and 1 in progress workflow jobs
[1598440398444] INFO  (18994 on paschal): Processing workflow jobs
[1598440400300] INFO  (18994 on paschal): There are 0 new and 1 in progress workflow jobs`

It repeats this indefinitely. 
I am running this on local env. The file I sent was a video link. The path for assetsInput and assetsoutputs are both path to my local machine (Ubuntu 20.04 LTS)

Any idea what could be wrong?

**Comment by PatrickKalkman** [comment]
What happens is that the workflow engine has picked up the request. It should create a job and multiple tasks for encoding the video file. The logging of the workflowencoder should give more information. See the README.md for more information.

**Comment by Zonalds** [comment]
I will keep triying. The error I get is this:

`[1598614387105] ERROR (30191 on paschal): An error occurred while trying to retrieve a new task. Error: connect ECONNREFUSED 127.0.0.1:8181

[1598614387105] INFO  (30191 on paschal): An error occurred while searching for encoding tasks. Err: Error: connect ECONNREFUSED 127.0.0.1:8181`
