### ISSUE TITLE
Question about the worker threads

### ISSUE THREAD

**Issue by michaelkuk** [PatrickKalkman/MiniVideoEncoder#294]
Hello and thank you for the time you are spending on this as the Node community could really use some easy-to-use encoding library.

However I do not understand the reasoning behind the usage of worker_threads here.`fluent-ffmpeg` is a wrapper for ffmpeg cli and therefore launches different OS process with its own threadpool - it does not block node main thread (that is unless there is some expensive ffmpeg stdout processing). 

Is there a benefit I am something I am not seeing in that approach?

Thanks and again - Nice job!

**Comment by PatrickKalkman** [comment]
Hi Michael,

It was something that I wanted to test. I wanted to see if it provided any benefits, but as you already mention there weren't any. What I am currently doing to scale is to spin up multiple encoder containers.

Have a nice day!
